### ISSUE TITLE
Removal of e-Tugra root certificate

### ISSUE THREAD

**Issue by nagaripratap** [microsoft/jacdac-esp32#12]
Description
Certifi 2023.07.22 removes root certificates from "e-Tugra" from the root store. These are in the process of being removed from Mozilla's trust store.

e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A).

Informations

Manifest Path : [scripts/ca-bundle.pem](https://github.com/microsoft/devicescript-esp32/blob/feae932bae00df1df125af1c7daa097a33eaf9a4/scripts/ca-bundle.pem#L3085)

**Comment by mmoskal** [comment]
Thank you, removed!
